// Conhecimento externo curado para o RAG da IAQ3D.
// São resumos técnicos originais com atribuição, não cópias integrais das fontes.
// Hierarquia: este corpus nunca substitui parâmetros ou conhecimento aprovado Quanton3D.

const REVIEWED_AT = '2026-09-02';

const SOURCES = {
  chituboxAccuracy: 'https://docs.chitubox.com/en-US/academy/a-detailed-analysis-of-the-factors-affecting-printing-accuracy',
  chituboxFailures: 'https://docs.chitubox.com/en-US/academy/all-you-need-to-know-about-failed-printing',
  formOrientation: 'https://formlabs.com/support/Model-Orientation/',
  formDelamination: 'https://formlabs.com/support/Delamination/',
  formPostCure: 'https://formlabs.com/support/Best-practices-for-post-curing-prints/',
  formFinish: 'https://formlabs.com/support/SLA-basic-finishing/',
  formMarks: 'https://formlabs.com/support/Removing-Support-Marks/',
  formPrint: 'https://formlabs.com/support/Best-practices-for-printing-with-Form-4-generation-printers/',
  prusaCalibration: 'https://help.prusa3d.com/article/resin-calibration-sl1-sl1s_112182',
  prusaWash: 'https://help.prusa3d.com/article/using-the-cw1-washing_112124',
  prusaTank: 'https://help.prusa3d.com/article/resin-tank-cleaning-sl1-sl1s_302488',
  lycheeTroubleshooting: 'https://doc.mango3d.io/doc/troubleshooting-print-failures/',
  lycheeLines: 'https://doc.mango3d.io/doc/j3d-tech-s-guide-to-resin-printing/troubleshooting-print-failures/layer-lines/',
  uvtools: 'https://github.com/sn4k3/UVtools',
};

function document({
  id,
  title,
  category,
  tags,
  content,
  sourceName,
  sourceUrl,
  confidence = 'alta',
  risk = 'medio',
  license = 'Resumo factual com atribuição; consultar a fonte original',
}) {
  return {
    id,
    title,
    category,
    tags,
    content,
    source: 'base_externa_curada',
    sourceName,
    sourceUrl,
    confidence,
    risk,
    license,
    reviewedAt: REVIEWED_AT,
  };
}

const EXTERNAL_KNOWLEDGE = [
  document({
    id: 'ext-chitubox-dimensional-exposure',
    title: 'Peça menor ou maior: influência da exposição na dimensão externa',
    category: 'calibracao_dimensional',
    tags: ['peça menor', 'subexposição', 'sobreexposição', 'dimensão XY', 'compensação'],
    content: 'Em dimensões externas, subexposição tende a produzir uma peça menor que o nominal porque a região periférica não polimeriza até o contorno previsto. Sobreexposição tende ao efeito oposto: crescimento externo, cantos arredondados e fechamento de detalhes negativos. A primeira correção é calibrar a exposição normal com corpo de prova; compensação XY só deve corrigir o erro residual de um processo já estável.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxAccuracy,
  }),
  document({
    id: 'ext-chitubox-xy-resolution',
    title: 'Resolução XY, tamanho da tela e distorção dimensional',
    category: 'calibracao_dimensional',
    tags: ['resolução XY', 'pixel', 'tela', 'build size', 'distorção'],
    content: 'A resolução em pixels e o tamanho físico configurado para a tela determinam a escala XY. Se resolução ou dimensões de tela forem cadastradas incorretamente no perfil da impressora, o modelo pode sair distorcido ou com escala diferente entre X e Y. Antes de compensar a peça, confirme o perfil exato da máquina e não confunda área física da tela com volume útil anunciado.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxAccuracy,
  }),
  document({
    id: 'ext-chitubox-z-accuracy',
    title: 'Precisão Z: altura de camada e estabilidade mecânica',
    category: 'calibracao_dimensional',
    tags: ['eixo Z', 'altura de camada', 'banding', 'folga', 'precisão Z'],
    content: 'A precisão no eixo Z depende da altura de camada e também da estabilidade mecânica. Perpendicularidade, retidão, paralelismo entre guia e fuso, aperto da plataforma e rigidez do conjunto influenciam a repetibilidade. Linhas em uma altura recorrente não devem ser tratadas apenas com exposição: inspecione movimento, folgas, acoplamento e a camada correspondente no arquivo.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxAccuracy,
  }),
  document({
    id: 'ext-chitubox-ipa-dimension',
    title: 'Lavagem prolongada pode alterar dimensão e forma',
    category: 'pos_processamento',
    tags: ['IPA', 'álcool', 'lavagem', 'inchaço', 'curvatura', 'dimensão'],
    content: 'Contato excessivo com solvente pode causar absorção, expansão ou curvatura em algumas resinas e geometrias finas. Para diagnosticar variação dimensional, padronize solvente, tempo, agitação e secagem; meça somente após a peça secar. O limite seguro deve vir da ficha técnica da resina Quanton3D, não de um tempo universal de outra marca.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxAccuracy,
  }),
  document({
    id: 'ext-chitubox-large-section-peel',
    title: 'Grandes seções por camada aumentam a carga de separação',
    category: 'orientacao_peel',
    tags: ['peel', 'seção transversal', 'área por camada', 'força', 'orientação'],
    content: 'Uma grande área curada simultaneamente aumenta fortemente a carga durante a separação do filme. O diagnóstico deve correlacionar a primeira falha com o preview da camada: saltos bruscos de área, superfícies planas paralelas ao tanque e massas largas elevam o esforço sobre suporte e peça. Reoriente para distribuir a seção e evite transformar exposição em compensação para uma geometria mal posicionada.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxFailures,
  }),
  document({
    id: 'ext-chitubox-suction-chamber',
    title: 'Câmara fechada e efeito de sucção',
    category: 'cavidades',
    tags: ['sucção', 'cavidade', 'ventilação', 'respiro', 'furo', 'peça oca'],
    content: 'Uma cavidade que fecha contra o filme pode formar diferença de pressão e aumentar a carga de separação. O primeiro furo deve comunicar a cavidade desde seu início, não apenas drenar ao final. Revise o preview camada a camada, crie caminho de entrada de ar e saída de resina e confirme que furos permanecem acessíveis durante lavagem e pós-cura.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxFailures,
    risk: 'alto',
  }),
  document({
    id: 'ext-chitubox-islands',
    title: 'Ilhas não suportadas iniciam falhas e fragmentos',
    category: 'suportes',
    tags: ['ilhas', 'islands', 'preview', 'fragmentos', 'suporte'],
    content: 'Uma ilha é uma região que começa sem ligação com a peça ou com suporte anterior. Ela cura no filme, pode se unir depois de forma deformada ou permanecer como fragmento no tanque. Use detecção de ilhas como triagem, confirme visualmente no preview e sustente a primeira camada estrutural da região, não apenas camadas posteriores.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxFailures,
    risk: 'alto',
  }),
  document({
    id: 'ext-chitubox-lift-speed',
    title: 'Velocidade de elevação e falha de separação',
    category: 'movimento',
    tags: ['lift speed', 'velocidade de elevação', 'peel', 'delaminação', 'suporte rompe'],
    content: 'Elevação agressiva pode aumentar a força instantânea de separação e romper contatos, camadas ou base. Não existe velocidade universal: filme, área da camada, viscosidade, distância e mecânica da impressora mudam o comportamento. Reduza em passos controlados quando a evidência apontar separação agressiva e mantenha as demais variáveis constantes.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxFailures,
  }),
  document({
    id: 'ext-chitubox-film-condition',
    title: 'Filme desgastado aumenta esforço e falhas locais',
    category: 'manutencao',
    tags: ['FEP', 'PFA', 'ACF', 'filme opaco', 'filme marcado', 'aderência'],
    content: 'Filme severamente desgastado, marcado ou contaminado pode elevar a aderência da camada e a carga de peel. Inspecione com o tanque vazio e iluminação adequada. Substitua por condição observada e instrução do fabricante, não por um número fixo de impressões. Uma falha sempre na mesma posição XY pede inspeção localizada do filme e do sistema óptico.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxFailures,
  }),
  document({
    id: 'ext-chitubox-support-contact',
    title: 'Contato do suporte: profundidade, diâmetro e distribuição',
    category: 'suportes',
    tags: ['contact depth', 'upper diameter', 'ponta', 'suporte leve', 'suporte médio'],
    content: 'Capacidade do suporte depende da geometria efetivamente curada no contato. Profundidade e diâmetro maiores aumentam a ligação, mas também a marca e o risco de arrancamento. Reforce primeiro contatos iniciais e regiões de maior carga; prefira distribuição coerente a poucos contatos brutais. Confirme se a ruptura ocorreu na ponta, no tronco ou na base.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxFailures,
  }),
  document({
    id: 'ext-chitubox-temperature',
    title: 'Temperatura baixa aumenta viscosidade e muda a cura',
    category: 'processo',
    tags: ['temperatura', 'viscosidade', 'resina fria', 'refluxo', 'subexposição'],
    content: 'Temperatura baixa eleva a viscosidade, dificulta o reenchimento entre camadas e pode reduzir a resposta de cura. Antes de aumentar exposição, registre a temperatura real da resina e estabilize o processo na faixa indicada pela ficha técnica Quanton3D. Aquecimento deve ser controlado; não use água quente, soprador ou improvisos junto à resina.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxFailures,
    risk: 'alto',
  }),
  document({
    id: 'ext-chitubox-optical-test',
    title: 'Falha fixa em XY: tela, luz e caminho óptico',
    category: 'hardware',
    tags: ['LCD', 'pixel morto', 'luz UV', 'falha localizada', 'posição XY'],
    content: 'Defeito que se repete na mesma posição XY pode indicar pixel morto, bloqueio, sujeira, filme danificado ou não uniformidade de luz. Mova um corpo de prova conhecido para outra região e execute o teste de exposição segundo o fabricante. Não olhe diretamente para UV intenso; use proteção ocular apropriada e não opere com proteções removidas.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxFailures,
    risk: 'alto',
  }),
  document({
    id: 'ext-formlabs-flat-orientation',
    title: 'Inclinar superfícies planas reduz área e carga por camada',
    category: 'orientacao_peel',
    tags: ['superfície plana', 'inclinação', 'orientação', 'força', 'peel'],
    content: 'Superfícies grandes e planas paralelas ao tanque concentram área e esforço. A orientação inclinada pode reduzir a área de cada camada e o contato simultâneo com o tanque, aumentando a chance de sucesso. O ângulo deve ser validado para a geometria; não transforme um valor de outro sistema em regra universal para toda impressora MSLA.',
    sourceName: 'Formlabs Support',
    sourceUrl: SOURCES.formOrientation,
  }),
  document({
    id: 'ext-formlabs-delamination-debris',
    title: 'Delaminação localizada: sujeira ou resíduo no tanque',
    category: 'falhas',
    tags: ['delaminação', 'resíduo', 'tanque', 'falha XY', 'fragmento'],
    content: 'Dano, sujeira ou resina curada no tanque pode bloquear luz em uma posição e impedir cura local. Preserve a evidência, remova fragmentos com ferramenta compatível e filtre a resina após falha. Evite ferramentas metálicas ou pontiagudas no filme. Se a falha acompanha a mesma posição física, priorize inspeção do tanque e caminho óptico.',
    sourceName: 'Formlabs Support',
    sourceUrl: SOURCES.formDelamination,
    risk: 'alto',
  }),
  document({
    id: 'ext-formlabs-postcure-warp',
    title: 'Empenamento e queda durante a pós-cura',
    category: 'pos_cura',
    tags: ['pós-cura', 'empenamento', 'sag', 'deformação', 'apoio'],
    content: 'Peças pesadas, longas, finas ou ainda com baixa rigidez podem ceder durante pós-cura se apoiadas de modo inadequado. Diferencie deformação já presente ao sair da impressora daquela criada na cura. Use apoio que preserve a geometria, distribuição uniforme de energia e procedimento específico da resina; tempo maior não corrige automaticamente cura desigual.',
    sourceName: 'Formlabs Support',
    sourceUrl: SOURCES.formPrint,
  }),
  document({
    id: 'ext-formlabs-support-removal',
    title: 'Momento de remover suportes depende do material',
    category: 'pos_processamento',
    tags: ['remoção de suporte', 'antes da cura', 'depois da cura', 'marca', 'empenamento'],
    content: 'Não existe regra universal para remover suporte sempre antes ou sempre depois da pós-cura. Remover ainda verde pode exigir menos força em alguns materiais; manter suporte durante a cura pode controlar empenamento em peças finas. Siga a ficha técnica da resina e valide força de corte, deformação e acabamento. Corte o contato em vez de arrancar.',
    sourceName: 'Formlabs Support',
    sourceUrl: SOURCES.formMarks,
  }),
  document({
    id: 'ext-formlabs-finishing-marks',
    title: 'Marca de suporte: relevo, cratera e acabamento',
    category: 'acabamento',
    tags: ['marca de suporte', 'lixa', 'cratera', 'relevo', 'microtrinca'],
    content: 'Material acima da superfície pode ser rebaixado de modo progressivo; uma cratera representa material perdido e pode exigir preenchimento ou aceitação dimensional. Esbranquiçamento e microtrinca indicam fratura local. Avalie contato, material, técnica de corte e momento de remoção antes de culpar apenas a pós-cura.',
    sourceName: 'Formlabs Support',
    sourceUrl: SOURCES.formFinish,
  }),
  document({
    id: 'ext-prusa-calibration-workflow',
    title: 'Calibração de resina exige pós-processo padronizado',
    category: 'calibracao',
    tags: ['calibração', 'corpo de prova', 'exposição', 'lavagem', 'pós-cura'],
    content: 'Compare exposições usando o mesmo arquivo, posição, camada, temperatura, lavagem, secagem e pós-cura. Avalie o corpo de prova somente depois do fluxo completo e registre o valor associado a cada amostra. Uma única peça bonita não basta: confirme dimensão, detalhes positivos e negativos, resistência e repetibilidade.',
    sourceName: 'Prusa Knowledge Base',
    sourceUrl: SOURCES.prusaCalibration,
  }),
  document({
    id: 'ext-prusa-wash-safety',
    title: 'Lavagem segura de peças impressas em resina',
    category: 'seguranca',
    tags: ['lavagem', 'luvas', 'solvente', 'resina líquida', 'IPA'],
    content: 'Peça recém-impressa, plataforma e utensílios permanecem contaminados por resina não curada. Use luvas nitrílicas, contenha respingos e siga a FISPQ/SDS da resina e do solvente. Lave até remover resíduo superficial, seque completamente antes da pós-cura e não descarte solvente contaminado na pia.',
    sourceName: 'Prusa Knowledge Base',
    sourceUrl: SOURCES.prusaWash,
    risk: 'alto',
  }),
  document({
    id: 'ext-prusa-tank-fragments',
    title: 'Fragmentos no tanque podem danificar filme e tela',
    category: 'seguranca_manutencao',
    tags: ['fragmento', 'tanque', 'tela quebrada', 'filtrar resina', 'falha anterior'],
    content: 'Resina curada remanescente após uma falha pode causar furos, geometria ausente e dano mecânico quando comprimida pela plataforma. Antes de reiniciar, execute o procedimento de limpeza compatível com a impressora, filtre a resina e inspecione o filme. Nunca force a plataforma contra um tanque possivelmente contaminado.',
    sourceName: 'Prusa Knowledge Base',
    sourceUrl: SOURCES.prusaTank,
    risk: 'alto',
  }),
  document({
    id: 'ext-lychee-layer-lines',
    title: 'Linhas isoladas podem vir de suporte, movimento ou processo',
    category: 'falhas',
    tags: ['layer lines', 'linhas horizontais', 'banding', 'pausa', 'temperatura'],
    content: 'Bandas ou linhas isoladas podem resultar de suporte insuficiente, elevação agressiva, temperatura baixa ou variável, ausência de espera, sucção em peça oca, pausa, adição de resina ou irregularidade no eixo. Anti-aliasing não corrige movimento Z nem instabilidade. Correlacione a altura da linha com o preview e o histórico da impressão.',
    sourceName: 'Lychee/Mango3D Documentation',
    sourceUrl: SOURCES.lycheeLines,
    confidence: 'media',
  }),
  document({
    id: 'ext-lychee-just-supports',
    title: 'Quando apenas raft e suportes imprimem',
    category: 'falhas',
    tags: ['só suportes', 'modelo soltou', 'raft', 'contato', 'ilha'],
    content: 'Se o raft e os troncos estão presentes, a adesão da plataforma funcionou. A investigação deve começar na união suporte-modelo e na primeira ilha perdida: contato insuficiente, distribuição inadequada, exposição normal baixa, seção grande ou sucção. Identifique onde cada suporte rompeu antes de engrossar toda a estrutura.',
    sourceName: 'Lychee/Mango3D Documentation',
    sourceUrl: SOURCES.lycheeTroubleshooting,
    confidence: 'media',
  }),
  document({
    id: 'ext-uvtools-file-analysis',
    title: 'Análise do arquivo fatiado antes de imprimir',
    category: 'arquivo_fatiado',
    tags: ['UVtools', 'arquivo', 'camada', 'análise', 'reparo'],
    content: 'UVtools permite visualizar camadas e inspecionar configurações gravadas no arquivo. Antes de culpar resina ou hardware, confirme que o arquivo contém as camadas esperadas, dimensões, altura e parâmetros corretos. Use reparos automáticos com cautela, mantenha o arquivo original e valide o resultado visualmente.',
    sourceName: 'UVtools GitHub',
    sourceUrl: SOURCES.uvtools,
    confidence: 'alta',
    license: 'AGPL-3.0; resumo original com atribuição',
  }),
  document({
    id: 'ext-uvtools-islands-overhangs',
    title: 'Detecção de ilhas e overhangs no arquivo fatiado',
    category: 'arquivo_fatiado',
    tags: ['UVtools', 'ilhas', 'overhangs', 'camada', 'suporte'],
    content: 'A análise do arquivo pode localizar ilhas e overhangs que começam sem sustentação suficiente. Detecção automática é triagem: ruído, pixels isolados e detalhes intencionais precisam de revisão humana. Verifique a primeira camada da região e assegure um caminho estrutural contínuo até a base.',
    sourceName: 'UVtools GitHub',
    sourceUrl: SOURCES.uvtools,
    license: 'AGPL-3.0; resumo original com atribuição',
  }),
  document({
    id: 'ext-uvtools-resin-traps-suction',
    title: 'Detecção de resin traps e suction cups',
    category: 'arquivo_fatiado',
    tags: ['UVtools', 'resin trap', 'suction cup', 'cavidade', 'drenagem'],
    content: 'Resin traps retêm material; suction cups criam cavidades fechadas em relação ao filme. A ferramenta pode indicar regiões suspeitas, mas o operador deve confirmar comunicação entre cavidade, furos e exterior ao longo de todas as camadas. Corrija o modelo ou a orientação antes de apenas aumentar suportes.',
    sourceName: 'UVtools GitHub',
    sourceUrl: SOURCES.uvtools,
    risk: 'alto',
    license: 'AGPL-3.0; resumo original com atribuição',
  }),
  document({
    id: 'ext-uvtools-empty-layers',
    title: 'Camadas vazias e interrupções no arquivo',
    category: 'arquivo_fatiado',
    tags: ['UVtools', 'camada vazia', 'arquivo corrompido', 'falha na altura Z'],
    content: 'Camada vazia no meio do arquivo interrompe a continuidade e pode produzir separação completa numa altura específica. Quando todas as peças falham no mesmo Z, examine as camadas correspondentes e refatie a partir do modelo original. Compare hash ou tamanho do arquivo após transferência quando houver suspeita de mídia defeituosa.',
    sourceName: 'UVtools GitHub',
    sourceUrl: SOURCES.uvtools,
    license: 'AGPL-3.0; resumo original com atribuição',
  }),
  document({
    id: 'ext-uvtools-wait-times',
    title: 'Tempos de espera fazem parte do ciclo de cada camada',
    category: 'movimento',
    tags: ['wait before cure', 'wait after cure', 'light off delay', 'rest time', 'refluxo'],
    content: 'O arquivo pode armazenar espera antes da cura, depois da cura e após movimentos. Esses tempos não são intercambiáveis. Espera antes da exposição permite acomodação e reenchimento; outras esperas atuam em fases diferentes. Ao migrar perfil entre fatiadores, confirme a semântica dos campos e o que o firmware realmente executa.',
    sourceName: 'UVtools GitHub',
    sourceUrl: SOURCES.uvtools,
    license: 'AGPL-3.0; resumo original com atribuição',
  }),
  document({
    id: 'ext-uvtools-format-settings',
    title: 'Parâmetros efetivos devem ser lidos no arquivo final',
    category: 'arquivo_fatiado',
    tags: ['UVtools', 'CTB', 'GOO', 'arquivo final', 'parâmetros', 'fatiador'],
    content: 'O projeto do fatiador e o arquivo entregue à impressora podem divergir por perfil, exportação ou formato. Leia no arquivo final exposição, camadas de base, transição, esperas, elevação e resolução. Isso ajuda a explicar diferença entre o que o operador lembra ter configurado e o que a máquina recebeu.',
    sourceName: 'UVtools GitHub',
    sourceUrl: SOURCES.uvtools,
    license: 'AGPL-3.0; resumo original com atribuição',
  }),
  document({
    id: 'ext-general-internal-vs-external',
    title: 'Dimensão externa e furo interno não usam a mesma leitura',
    category: 'calibracao_dimensional',
    tags: ['furo menor', 'diâmetro interno', 'dimensão externa', 'tolerância', 'encaixe'],
    content: 'Exposição alta pode aumentar o contorno externo e fechar furos; exposição baixa pode reduzir paredes e dimensões externas. Meça positivos e negativos separadamente. Só depois da exposição calibrada use compensações externa e interna conforme a convenção do fatiador. Uma única escala global pode corrigir o exterior e piorar encaixes internos.',
    sourceName: 'Síntese Quanton3D de fontes oficiais',
    sourceUrl: SOURCES.chituboxAccuracy,
  }),
  document({
    id: 'ext-general-diagnostic-pattern',
    title: 'Padrão XY, padrão Z e falha de geometria',
    category: 'diagnostico',
    tags: ['diagnóstico', 'posição XY', 'altura Z', 'geometria', 'causa raiz'],
    content: 'Falha fixa em XY aponta primeiro para filme, luz, tela ou contaminação localizada. Falha fixa em Z aponta para camada do arquivo, eixo ou evento mecânico. Falha que acompanha apenas uma geometria aponta para malha, orientação, ilha, suporte ou sucção. Esse padrão deve ser identificado antes de alterar exposição.',
    sourceName: 'Síntese Quanton3D de fontes oficiais',
    sourceUrl: SOURCES.chituboxFailures,
  }),
  document({
    id: 'ext-general-one-variable',
    title: 'Diagnóstico controlado: alterar uma variável por vez',
    category: 'metodo',
    tags: ['uma variável', 'teste controlado', 'registro', 'repetibilidade'],
    content: 'Preserve fotos e parâmetros, formule uma hipótese, altere uma variável e repita o mesmo corpo de prova. Mudanças simultâneas podem eliminar o sintoma sem provar a causa. Registre resina, lote, impressora, temperatura, arquivo, exposição, movimentos, lavagem e pós-cura para transformar acerto ocasional em processo reproduzível.',
    sourceName: 'CHITUBOX Docs',
    sourceUrl: SOURCES.chituboxFailures,
  }),
];

export function validateExternalKnowledge(documents = EXTERNAL_KNOWLEDGE) {
  const required = ['id', 'title', 'category', 'tags', 'content', 'sourceName', 'sourceUrl', 'confidence', 'risk', 'reviewedAt'];
  const ids = new Set();

  for (const item of documents) {
    for (const field of required) {
      if (!item[field] || (Array.isArray(item[field]) && !item[field].length)) {
        throw new Error(`Documento externo inválido: ${item.id || 'sem-id'} sem ${field}`);
      }
    }
    if (ids.has(item.id)) throw new Error(`Documento externo duplicado: ${item.id}`);
    if (!/^https:\/\//.test(item.sourceUrl)) throw new Error(`Fonte externa inválida: ${item.id}`);
    ids.add(item.id);
  }

  return true;
}

validateExternalKnowledge();

export default EXTERNAL_KNOWLEDGE;
